### ISSUE TITLE
Specs fail on initial project setup when following README instructions (before asset building)

### ISSUE THREAD

**Issue by SansSeryph** [wnbrb/wnb-rb-site#219]
**Describe the bug**
When setting up the project for the first time and following the steps outlined in the README, running RSpec as described on step 4 at that point in time will cause a number of specs to fail (see below for output).

**To Reproduce**
1. From a fresh clone of the repo, run `make setup`
2. Run `rspec`
3. Observe output from rspec run

**Expected behavior**
Specs should pass after running `make setup`

**Screenshots**
Please see the Additonal context section below for RSpec run output

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

<details>
<summary>RSpec run output</summary>

```
.....................................................................................FFFFFFFFFFF........

Failures:

  1) Admin login system enables me to register to WNB.rb as admin
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/admin_login_system_spec.rb:16:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  2) Admin login system admin registered enables me to reset WNB.rb admin password
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/admin_login_system_spec.rb:40:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  3) Admin login system admin registered admin not logged in enables me to login to WNB.rb admin
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/admin_login_system_spec.rb:52:in `block (4 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  4) Admin login system admin registered admin is logged in enables me to logout from WNB.rb admin
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/admin_login_system_spec.rb:63:in `block (4 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  5) Managing events deletes an event
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/managing_events_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  6) Managing events creates an event 
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/managing_events_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  7) Managing events creates an event with valid data creates an event
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/managing_events_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  8) Managing events creates an event with invalid data shows errors
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/managing_events_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  9) Managing speakers create a speaker 
     Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

     ActionView::Template::Error:
       The asset "admin.js" is not present in the asset pipeline.
     # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
     # ./spec/system/managing_speakers_spec.rb:12:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Sprockets::Rails::Helper::AssetNotFound:
     #   The asset "admin.js" is not present in the asset pipeline.
     #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  10) Managing speakers create a speaker with valid data creates an event
      Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

      ActionView::Template::Error:
        The asset "admin.js" is not present in the asset pipeline.
      # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
      # ./spec/system/managing_speakers_spec.rb:12:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # Sprockets::Rails::Helper::AssetNotFound:
      #   The asset "admin.js" is not present in the asset pipeline.
      #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

  11) Managing speakers create a speaker with invalid data shows errors
      Failure/Error: <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>

      ActionView::Template::Error:
        The asset "admin.js" is not present in the asset pipeline.
      # ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'
      # ./spec/system/managing_speakers_spec.rb:12:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # Sprockets::Rails::Helper::AssetNotFound:
      #   The asset "admin.js" is not present in the asset pipeline.
      #   ./app/views/layouts/admin.html.erb:17:in `_app_views_layouts_admin_html_erb___3707253898526032420_46400'

Finished in 9.16 seconds (files took 1.51 seconds to load)
104 examples, 11 failures

Failed examples:

rspec ./spec/system/admin_login_system_spec.rb:9 # Admin login system enables me to register to WNB.rb as admin
rspec ./spec/system/admin_login_system_spec.rb:27 # Admin login system admin registered enables me to reset WNB.rb admin password
rspec ./spec/system/admin_login_system_spec.rb:46 # Admin login system admin registered admin not logged in enables me to login to WNB.rb admin
rspec ./spec/system/admin_login_system_spec.rb:60 # Admin login system admin registered admin is logged in enables me to logout from WNB.rb admin
rspec ./spec/system/managing_events_spec.rb:46 # Managing events deletes an event
rspec ./spec/system/managing_events_spec.rb:18 # Managing events creates an event 
rspec ./spec/system/managing_events_spec.rb:21 # Managing events creates an event with valid data creates an event
rspec ./spec/system/managing_events_spec.rb:37 # Managing events creates an event with invalid data shows errors
rspec ./spec/system/managing_speakers_spec.rb:17 # Managing speakers create a speaker 
rspec ./spec/system/managing_speakers_spec.rb:20 # Managing speakers create a speaker with valid data creates an event
rspec ./spec/system/managing_speakers_spec.rb:37 # Managing speakers create a speaker with invalid data shows errors
```

</details>

**Comment by SansSeryph** [comment]
Hi there, I noticed a small thing I could help with to start getting familiar with the process of contributing to the project! I started a PR to get the ball rolling: https://github.com/wnbrb/wnb-rb-site/pull/220

**Comment by SansSeryph** [comment]
PR has been merged. Closing the issue now :)
